# Generated by Django 6.0.4 on 2026-05-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='available',
            new_name='is_open',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='park',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parks/'),
        ),
        migrations.AddField(
            model_name='trail',
            name='duration_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trails/'),
        ),
        migrations.AddField(
            model_name='trail',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='difficulty',
            field=models.CharField(choices=[('Fácil', 'Fácil'), ('Moderada', 'Moderada'), ('Difícil', 'Difícil')], max_length=10),
        ),
    ]
