# Generated by Django 6.0.4 on 2026-05-03 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_available_event_is_open_event_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name': 'Funcionamento', 'verbose_name_plural': 'Funcionamentos'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='park',
            options={'verbose_name': 'Parque', 'verbose_name_plural': 'Parques'},
        ),
        migrations.AlterModelOptions(
            name='trail',
            options={'verbose_name': 'Trilha', 'verbose_name_plural': 'Trilhas'},
        ),
        migrations.AlterField(
            model_name='availability',
            name='close_time',
            field=models.TimeField(verbose_name='Horário de fechamento'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Funcionamento ativo'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='open_time',
            field=models.TimeField(verbose_name='Horário de abertura'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.park', verbose_name='Parque'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='event',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.park', verbose_name='Parque'),
        ),
        migrations.AlterField(
            model_name='park',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='park',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parks/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='park',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='difficulty',
            field=models.CharField(max_length=50, verbose_name='Dificuldade'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='duration_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duração (min)'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trails/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Aberta'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='length_km',
            field=models.FloatField(verbose_name='Distância (km)'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.park', verbose_name='Parque'),
        ),
    ]
