# Generated by Django 6.0.4 on 2026-05-03 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_availability_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biodiversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='biodiversity/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Biodiversidade',
                'verbose_name_plural': 'Biodiversidade',
            },
        ),
        migrations.CreateModel(
            name='Waterfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='waterfalls/', verbose_name='Imagem')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.park', verbose_name='Parque')),
            ],
            options={
                'verbose_name': 'Cachoeira',
                'verbose_name_plural': 'Cachoeiras',
            },
        ),
    ]
