# Generated by Django 6.0.4 on 2026-05-03 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_biodiversity_waterfall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterfall',
            name='park',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.park', verbose_name='Parque'),
        ),
    ]
