# Generated by Django 6.0.4 on 2026-05-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_waterfall_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterfall',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localização'),
        ),
    ]
